[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
remappings = [
    "@aave/=node_modules/@aave/",
    "@chainlink/=node_modules/@chainlink/",
    "@ensdomains/=node_modules/@ensdomains/",
    "@eth-optimism/=node_modules/@eth-optimism/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@zondax/=node_modules/@zondax/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
    "solidity-cborutils/=node_modules/solidity-cborutils/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config